Set Shell zsh
Sleep 5.5s
Type "git stp"
Sleep 1s
Enter
Sleep 3.5s
Type "git diff"
Enter
Sleep 2.5s
Type "jut"
Backspace
Type "st branch readme-add-checkov"
Sleep 1.5s
Enter
Sleep 1s
Type "git add R"
Tab
Enter
Type "git cim '"
Sleep 9s
Escape
Type "[200~🪘"
Escape
Type "[201~ [readme]"
Sleep 1.5s
Type " mention Checkov"
Sleep 3.5s
Type " is "
Sleep 500ms
Type "a"
Backspace
Type "here'"
Sleep 1s
Left 16
Type "that "
Sleep 1.5s
Enter
Sleep 500ms
Type "just pr"
Sleep 500ms
Enter
Sleep 52.5s
Type "just merge"
Enter
Sleep 9.5s
Ctrl+D

