name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

# global permissions
permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: chicks-net
          numOfAssignee: 1
          allowSelfAssign: true
