---
name: EditorConfig

# Validates that files conform to .editorconfig using the
# editorconfig-checker GitHub action. Runs over the whole repo.

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - .editorconfig
  pull_request:
    paths:
      - '**'
      - .editorconfig

# global permissions
permissions: {}

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # v2.2.0

      - name: Run editorconfig-checker
        run: editorconfig-checker
