---
name: Validate Renovate config

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/renovate.json'
      - '.github/workflows/renovate-validate.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/renovate.json'
      - '.github/workflows/renovate-validate.yml'
  workflow_dispatch:

# global permissions
permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Validate renovate.json
        uses: docker://ghcr.io/renovatebot/renovate@sha256:a9fc5b7fee6d7b8887e79a0286f0a54bd1fdfa9b28ac38e6e76d0283394955b5
        with:
          args: renovate-config-validator .github/renovate.json
